### ISSUE TITLE
Windows Explorer crashes after interacting with the tray icon

### ISSUE THREAD

**Issue by Flaflo** [reserfodium/VirtualDesktopIndicator#3]
when you click the icon twice and then try to click on a window, explorer restarts. probably because the task view was already open or something.

_Originally posted by @ayunami2000 in https://github.com/reserfodium/VirtualDesktopIndicator/issues/1#issuecomment-540755066_

**Comment by Flaflo** [comment]
@ayunami2000 I could not reproduce this bug, it does what it is intended to do when I press on the traybar icon. I am on the latest Windows Version 1903.

What are your Computer Sepcs?

**Comment by ayunami2000** [comment]
![image](https://user-images.githubusercontent.com/24785136/66789792-30691980-eebb-11e9-8b41-fc3b6a5ff097.png)
Windows 10 Home Version 1903
NVIDIA & Intel (50% of the time every issue with this laptop is because of the two graphics cards)

Also I think I had clicked on the window almost immediately after clicking on the icon in the taskbar. May have had something to do with it

**Comment by vklachkov** [comment]
Hi everyone! I am the maintainer of this repository - reserfodium. But I lost access to this account. Thank you very much for your interest. Development continues in [this repository](https://github.com/0gdump/windows-virtualdesktopindicator). Check out latest release, I fixed some bugs and add new features.
